# Generated by Django 2.2.4 on 2020-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Best_Course', models.CharField(choices=[('Android Development', 'Android Development'), ('Web Technologies', 'Web Technologies'), ('Machine Learning/Artificial Intelligence', 'Machine Learning/Artificial Intelligence'), ('Database Systems', 'Database Systems'), ('OOP and Data Structures', 'OOP and Data Structures'), ('Computer Networks', 'Computer Networks'), ('Project Management', 'Project Management')], max_length=50)),
                ('Best_Language', models.CharField(choices=[('Java/Kotlin/Swift', 'Java/Kotlin/Swift'), ('C++/C#', 'C++/C#'), ('HTML/CSS/BOOTSTRAP', 'HTML/CSS/BOOTSTRAP'), ('PHP/JS', 'PHP/JS'), ('Python/R', 'Python/R')], max_length=50)),
                ('Certification', models.CharField(choices=[('None', 'None'), ('Mobile Application Development', 'Mobile Application Development'), ('Web Development', 'Web Development'), ('Web Designing', 'Web Designing'), ('Unity', 'Unity')], max_length=50)),
                ('Interested_Area', models.CharField(choices=[('Android', 'Android'), ('Web', 'Web'), ('Machine Learning', 'Machine Learning'), ('Designing', 'Designing'), ('Development', 'Development'), ('Management', 'Management'), ('Teaching', 'Teaching')], max_length=50)),
                ('Coding_Skills', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=50)),
                ('Communication_Skills', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=50)),
                ('Mangerial_Skills', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=50)),
                ('Self_Learning', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=50)),
                ('Reading_Writing_Skills', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=50)),
                ('Working_Strategy', models.CharField(choices=[('Team', 'Team'), ('Individual', 'Individual')], max_length=50)),
                ('Solution_Provider', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
            ],
        ),
    ]
