# Generated by Django 2.2.4 on 2020-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCS', '0002_formdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdb',
            name='Suggestion',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
