# Generated by Django 2.2.4 on 2020-02-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCS', '0003_formdb_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
