# Generated by Django 2.2.4 on 2020-02-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCS', '0004_auto_20200228_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdb',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
